Entities and repos for Juror Summons Replies
hmcts/juror-sql-support-library pull request #11
Opened 2023-12-08 17:21 UTC by Matt-Smith-CGI

**Before creating a pull request make sure that:**

- [X] commit messages are meaningful and follow good commit message guidelines

### Change description ###

-Added relevant classes for Juror Summons Reply
-Added generator tags to relevant fields
-Added relevant repos for Juror Summons

2023-12-11 11:12 UTC, Ben-Edwards-cgi requested changes

2023-12-11 11:12 UTC, Ben-Edwards-cgi commented on src/main/java/uk/gov/hmcts/juror/support/sql/entity/AbstractJurorResponse.java
> +
Space not needed

2023-12-11 11:12 UTC, Ben-Edwards-cgi commented on src/main/java/uk/gov/hmcts/juror/support/sql/entity/AbstractJurorResponse.java
> +public class AbstractJurorResponse extends Address implements Serializable {
Should be an abstract class as we do not want this to be instantiated by itself

2023-12-11 11:12 UTC, Ben-Edwards-cgi commented on src/main/java/uk/gov/hmcts/juror/support/sql/entity/AbstractJurorResponse.java
> +    private LocalDate dateReceived;
Needs date generator

2023-12-11 11:12 UTC, Ben-Edwards-cgi commented on src/main/java/uk/gov/hmcts/juror/support/sql/entity/AbstractJurorResponse.java
> +    private String processingStatus;
Needs default value

2023-12-11 11:12 UTC, Ben-Edwards-CGI commented on src/main/java/uk/gov/hmcts/juror/support/sql/entity/AbstractJurorResponse.java
> +    private Boolean residency;
All columns need default can be done using @FixedValueGenerator("your default")

2023-12-11 11:12 UTC, Ben-Edwards-CGI commented on src/main/java/uk/gov/hmcts/juror/support/sql/entity/jurorresponse/Address.java
> +    @RegexGenerator(regex = "[0-9]{0,9} [A-Z]{5,15} (Road|Lane|Gate|Close|Avenue|Street|Way|Drive|Gardens|Crescent|"
Regex can be moved to Constants class

2023-12-11 11:12 UTC, Ben-Edwards-CGI commented on src/main/java/uk/gov/hmcts/juror/support/sql/entity/jurorresponse/Address.java
> +    @RegexGenerator(regex = "(Apartment|Suite|Room|Floor|Box) Number [0-9]{1,3}")
Regex can be moved to Constants class

2023-12-11 11:12 UTC, Ben-Edwards-CGI commented on src/main/java/uk/gov/hmcts/juror/support/sql/entity/jurorresponse/DigitalResponse.java
> +    @Builder.Default
Needs default using @FixedValueGenerator.
(Same for all fields with no generator)

2023-12-11 11:12 UTC, Ben-Edwards-CGI commented on src/main/java/uk/gov/hmcts/juror/support/sql/entity/jurorresponse/PaperResponse.java
> +    private Boolean mentalHealthCapacity;
Needs defaults

2023-12-11 11:12 UTC, Ben-Edwards-CGI commented on src/main/java/uk/gov/hmcts/juror/support/sql/entity/jurorresponse/ReasonableAdjustments.java
> +@Table(name = "t_reasonable_adjustments", schema = "juror_mod")
Any constant table (annotation with t_) is not needed

2023-12-11 11:12 UTC, Ben-Edwards-CGI commented on src/main/java/uk/gov/hmcts/juror/support/sql/entity/jurorresponse/ReplyType.java
> +@Table(name = "t_reply_type", schema = "juror_mod")
Class not needed as we can use Id's instead

2023-12-11 11:12 UTC, Ben-Edwards-CGI commented on src/main/java/uk/gov/hmcts/juror/support/sql/repository/JurorDigitalResponseRepository.java
> +    }
We only use repositories to save as such no methods are needed

2023-12-11 11:12 UTC, Ben-Edwards-CGI commented on src/main/java/uk/gov/hmcts/juror/support/sql/repository/JurorPaperResponseRepository.java
> +    }
Methods not needed

2023-12-11 12:36 UTC, Ben-Edwards-CGI requested changes

2023-12-11 12:36 UTC, Ben-Edwards-CGI commented on src/main/java/uk/gov/hmcts/juror/support/sql/entity/jurorresponse/DigitalResponse.java
> +    @FixedValueGenerator("d")
Should default to null

2023-12-11 12:36 UTC, Ben-Edwards-CGI commented on src/main/java/uk/gov/hmcts/juror/support/sql/entity/jurorresponse/DigitalResponse.java
> +    private String deferralReason;
Should default to null

2023-12-11 12:36 UTC, Ben-Edwards-CGI commented on src/main/java/uk/gov/hmcts/juror/support/sql/entity/jurorresponse/DigitalResponse.java
> +    @FixedValueGenerator("true")
Should default to null

2023-12-11 12:36 UTC, Ben-Edwards-CGI commented on src/main/java/uk/gov/hmcts/juror/support/sql/entity/jurorresponse/DigitalResponse.java
> +    @FixedValueGenerator("false")
Should default to null

2023-12-11 12:36 UTC, Ben-Edwards-CGI commented on src/main/java/uk/gov/hmcts/juror/support/sql/entity/jurorresponse/DigitalResponse.java
> +    @FixedValueGenerator("false")
Should default to null

2023-12-11 12:36 UTC, Ben-Edwards-CGI commented on src/main/java/uk/gov/hmcts/juror/support/sql/entity/jurorresponse/DigitalResponse.java
> +    @FixedValueGenerator("false")
Should default to null

2023-12-11 12:36 UTC, Ben-Edwards-CGI commented on src/main/java/uk/gov/hmcts/juror/support/sql/entity/jurorresponse/DigitalResponse.java
> +    )
Should default to null

2023-12-11 12:36 UTC, Ben-Edwards-CGI commented on src/main/java/uk/gov/hmcts/juror/support/sql/entity/jurorresponse/DigitalResponse.java
> +    @FirstNameGenerator
Should default to null

2023-12-11 12:36 UTC, Ben-Edwards-CGI commented on src/main/java/uk/gov/hmcts/juror/support/sql/entity/jurorresponse/DigitalResponse.java
> +    @LastNameGenerator
Should default to null

2023-12-11 12:36 UTC, Ben-Edwards-CGI commented on src/main/java/uk/gov/hmcts/juror/support/sql/entity/jurorresponse/DigitalResponse.java
> +    @FixedValueGenerator("ill")
Should default to null

2023-12-11 12:36 UTC, Ben-Edwards-CGI commented on src/main/java/uk/gov/hmcts/juror/support/sql/entity/jurorresponse/DigitalResponse.java
> +    @EmailGenerator
Should default to true

2023-12-11 12:36 UTC, Ben-Edwards-CGI commented on src/main/java/uk/gov/hmcts/juror/support/sql/entity/jurorresponse/ReasonableAdjustments.java
> +}
Not needed can use id

2023-12-11 16:40 UTC, Ben-Edwards-CGI requested changes

2023-12-11 16:40 UTC, Ben-Edwards-cgi commented on src/main/java/uk/gov/hmcts/juror/support/sql/entity/AbstractJurorResponse.java
> +    private String processingStatus;
Should be: 

  @Column(name = "processing_status")
    @Enumerated(EnumType.STRING)
    @FixedValueGenerator("ProcessingStatus.TODO")
    private ProcessingStatus processingStatus = ProcessingStatus.TODO;

2023-12-12 10:35 UTC, Matt-Smith-CGI reviewed
reviewed

2023-12-12 10:37 UTC, Ben-Edwards-CGI approved these changes

2023-12-12 10:37 UTC, merged